### ISSUE TITLE
breadcrumb and title overlap on single blog post pages

### ISSUE THREAD

**Issue by rcrath** [digiah/dahiweb#10]
The breadcrumb and the Title of blog posts interfere with each other when the screen is at certain widths.  Narrow enough and the breadcrumb drops under the title, wide enough, they remain separate, but inbetween looks like image below.  Maybe we could remove breadcrumbs altogether? Our architecture is pretty shallow, there is a menu at the top, and the logo, as is standard, send you to the home page.  I think the breadcrumb is redundant as it just gives the home page and the one layer deep you happen to be on at the moment, which echoes the title of the page, also redundant without providing any extra paths or navigation cues or such.  Remove?  Unless you all object, let's just turn breadcrumbs off plz.  
![screenshot from 2017-12-12 18-35-24](https://user-images.githubusercontent.com/944636/33922137-b190f38a-df6c-11e7-8bd9-531d4503d980.png)

**Comment by damg70** [comment]
this is classic "responsive design" error that resides at the theme level. it's not really something we can hack out, so we might 1) report the bug to the people who make the theme, and 2) follow @rcrath suggestion to drop them entirely.

**Comment by rcrath** [comment]
turned off breadcrumbs
