### ISSUE TITLE
footer errors

### ISSUE THREAD

**Issue by rcrath** [digiah/dahiweb#13]
I accidentally opened up an edit window for the footer with the copyright, etc info in it, and wp complained of 24 errors.  @kelseykato or @damg70 could you check this.

**Comment by damg70** [comment]
i don' see any errors in the javascript console. it looks like they are internal wordpress parser errors that are based on it not expecting to see HTML in the footer... the pop-up error says that the "<" is an unexpected character at line 1, col 1. It doesn't look like it is breaking the site.
