### ISSUE TITLE
Add explanation under Arts Humantities Data 

### ISSUE THREAD

**Issue by kelseykato** [digiah/dahiweb#8]
Explanation detailing what Arts humantities data category represents

**Comment by rcrath** [comment]
@damg70 please post a draft here.  You named it!

**Comment by damg70** [comment]
ART.HUMANITIES.DATA is DAHI's video blog that features interviews with various figures on campus and in our community, with a focus on those working in the visual and performing arts. We try to integrate dialog with samples of the work that the subject is doing, blending an intentionally skin-of-the-teeth shooting aesthetic with an editing approach that evokes the now-classic styles what theorist [Laura U Marks](https://www.dukeupress.edu/The-Skin-of-the-Film) calls "intercultural cinema." In 2018 DAHI hopes to return to this series with new interviews.

**Comment by rcrath** [comment]
@damg70 update? Discuss at first Jan meeting?

**Comment by rcrath** [comment]
@damg70 update?

**Comment by damg70** [comment]
draft provided two comments above, on dec 14.

**Comment by rcrath** [comment]
Sorry, my miss. Please delete the last sentence about 2018 and post in appropriate spot. Do we know where that is?
